all:
  hosts:
    node1:
      ansible_host: 192.168.5.1
      ip: 192.168.5.1
      access_ip: 192.168.5.1
      ansible_user: rocky
      ansible_sudo_pass: rockylinux
    node2:
      ansible_host: 192.168.5.2
      ip: 192.168.5.2
      access_ip: 192.168.5.2
      ansible_user: rocky
      ansible_sudo_pass: rockylinux
    node3:
      ansible_host: 192.168.5.3
      ip: 192.168.5.3
      access_ip: 192.168.5.3
      ansible_user: rocky
      ansible_sudo_pass: rockylinux
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
